name: Danger
on:
  pull_request_target:
    paths-ignore:
      - .danger.php
      - .github/**
  check_run:

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1

      - name: Composer Install
        run: composer install
